version: '3.8'
services:
  crog:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis
    restart: unless-stopped
    env_file:
      - path: .env.default
      - path: .env
        required: false
  redis:
    image: redis:alpine
