name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.11.2-alpine-build
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: make test
        continue-on-error: true
      - name: Build
        run: make
      - name: Build release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
            mkdir crog-${{github.ref_name}}
            cp bin/crog README.md LICENSE crog-${{github.ref_name}}/
            tar czpf crog-${{github.ref_name}}.tar.gz crog-${{github.ref_name}}
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            crog-${{github.ref_name}}.tar.gz
